# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CagedMcpServer < Formula
  desc "Model Context Protocol server for AI coding agents"
  homepage "https://github.com/caged-dev/mcp-server"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_darwin_amd64.tar.gz"
      sha256 "02eb596a51e33dac0a131eebeb11d92a94ef21a4de1a72c37f835de1c8ff7703"

      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_darwin_arm64.tar.gz"
      sha256 "cdec1f9dad2945ffc15aca26245c771c4c1c17dacf599afabf0fb2b19684dd73"

      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_linux_amd64.tar.gz"
      sha256 "1851bdda9799d7280b6e4902c324085aba8c39080a42715da3f6e47a467f093b"
      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_linux_arm64.tar.gz"
      sha256 "c2861a7a7cc522f158b5c5c8fe7a9a8980173e39059f50d1574fee73cc39be3d"
      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/caged-mcp-server", "--version"
  end
end
