# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caged < Formula
  desc "CLI for the Caged AI Agent Sandbox Platform"
  homepage "https://caged.dev"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.4/caged_0.1.4_darwin_amd64.tar.gz"
      sha256 "1559b4ea622170ce184cdb69292ce52f54f55ab5cc1a7b4dc721323f26479747"

      define_method(:install) do
        bin.install "caged"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.4/caged_0.1.4_darwin_arm64.tar.gz"
      sha256 "5d84cd2421ad8c999c3986dc44e72d0490cc25cc890498c6279592290bb50f78"

      define_method(:install) do
        bin.install "caged"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.4/caged_0.1.4_linux_amd64.tar.gz"
      sha256 "2824f7b62d9a753882f12b4906adae216eebf7d7b59be91a3a88c359b997951e"
      define_method(:install) do
        bin.install "caged"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.4/caged_0.1.4_linux_arm64.tar.gz"
      sha256 "f24194eaffddd95a13453009ca1424cb86a2d131e3bdade81ea1f31ce9b7af74"
      define_method(:install) do
        bin.install "caged"
      end
    end
  end

  test do
    system "#{bin}/caged", "version"
  end
end
