# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CagedAgent < Formula
  desc "Lightweight agent that runs inside Caged sandbox VMs"
  homepage "https://github.com/caged-dev/agent"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_darwin_amd64.tar.gz"
      sha256 "bd36fc719911db05ff9baeeb8e6d51b93717d0d7eeaca90817c969c966cecdac"

      define_method(:install) do
        bin.install "caged-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_darwin_arm64.tar.gz"
      sha256 "c456e7811644187ae6a4728ff6dfa3f5ccf953b155bc3124b6b826f44f676fd0"

      define_method(:install) do
        bin.install "caged-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_linux_amd64.tar.gz"
      sha256 "519e6d8e518b7b6e73671dbdab34d70f32bfc4b7129e8046cd1b8c089f889a09"
      define_method(:install) do
        bin.install "caged-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_linux_arm64.tar.gz"
      sha256 "8f33d4a2823c21cba5f00e1cfddee9ab9ef8baa1e0528e1f20c06edb15e853e3"
      define_method(:install) do
        bin.install "caged-agent"
      end
    end
  end

  test do
    system "#{bin}/caged-agent", "--version"
  end
end
