# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CagedAgent < Formula
  desc "Lightweight agent that runs inside Caged sandbox VMs"
  homepage "https://github.com/caged-dev/agent"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_darwin_amd64.tar.gz"
      sha256 "31cef63a0b5e41a7d0d84885e2b9c2a2c742635e209c636abf51836d8358ce07"

      define_method(:install) do
        bin.install "caged-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_darwin_arm64.tar.gz"
      sha256 "ea8398cc5327ca8c7c3b95976274d3cb50f9fb6fd13c7d47ef636544cb63d1e2"

      define_method(:install) do
        bin.install "caged-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_linux_amd64.tar.gz"
      sha256 "39bf00fc32bbc3eda49017f14aabd2c35afe0b80e0ff690f4e11679b24d60b87"
      define_method(:install) do
        bin.install "caged-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/agent/releases/download/v0.1.0/caged-agent_0.1.0_linux_arm64.tar.gz"
      sha256 "e63725868212fb6d84625758c3c037df9f2170d6f096df37da4518919d68c4f7"
      define_method(:install) do
        bin.install "caged-agent"
      end
    end
  end

  test do
    system "#{bin}/caged-agent", "--version"
  end
end
