# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caged < Formula
  desc "CLI for the Caged AI Agent Sandbox Platform"
  homepage "https://caged.dev"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.11/caged_0.1.11_darwin_amd64.tar.gz"
      sha256 "83b63c5338f033f86c43acc66e6191f5510d48e03d87d90bec3d6fe03193b903"

      define_method(:install) do
        bin.install "caged"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.11/caged_0.1.11_darwin_arm64.tar.gz"
      sha256 "1df03f7076e536a8a0c4df86794b8c108ff379da706283c884632b77c7edd7e2"

      define_method(:install) do
        bin.install "caged"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.11/caged_0.1.11_linux_amd64.tar.gz"
      sha256 "d1fb271798944d7553b519cda17b0869a45fd119c27a6e0f94d37f8d3408333e"
      define_method(:install) do
        bin.install "caged"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/cli/releases/download/v0.1.11/caged_0.1.11_linux_arm64.tar.gz"
      sha256 "4a8eb6d611c1c25d8f5b10021f10bbf5839b5d1d2c37858b5ad791632c3f8624"
      define_method(:install) do
        bin.install "caged"
      end
    end
  end

  test do
    system "#{bin}/caged", "version"
  end
end
