# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CagedMcpServer < Formula
  desc "Model Context Protocol server for AI coding agents"
  homepage "https://github.com/caged-dev/mcp-server"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_darwin_amd64.tar.gz"
      sha256 "886f1c1fffbf7cac145fb9b3e32c89e08b28ad3addace284aca7008f4806a4ac"

      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_darwin_arm64.tar.gz"
      sha256 "e93148a0573d0eab97e004ed3fce2ece89fb1fed88b709a6c38a3c77209fde3f"

      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_linux_amd64.tar.gz"
      sha256 "9aaf6675dcec4551163b16312a2de621b1e5c2d342e11d9ddd97ab0744395ddf"
      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_linux_arm64.tar.gz"
      sha256 "fc260d85dd499431e37dd03e37299c37f9e0c7d70df0d440df8823954f136679"
      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/caged-mcp-server", "--version"
  end
end
