# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CagedMcpServer < Formula
  desc "Model Context Protocol server for AI coding agents"
  homepage "https://github.com/caged-dev/mcp-server"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_darwin_amd64.tar.gz"
      sha256 "4645a82775183c9f18d32b74199cd6a7b166234220ee03225bdef77c1d7b5ef0"

      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_darwin_arm64.tar.gz"
      sha256 "bd75c511ad508b02c65ead53c8d021910afe688c8998c4f13f79e8b726dea870"

      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_linux_amd64.tar.gz"
      sha256 "5c1dcaced4beea31291e1eeeb49eec6b08b5a8804f27375ef5695f507115967c"
      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caged-dev/mcp-server/releases/download/v0.1.0/caged-mcp-server_0.1.0_linux_arm64.tar.gz"
      sha256 "aa2bbcffdaa5ee224309622d7fb93e695e923f8d244288f426f93d51ecf9f185"
      define_method(:install) do
        bin.install "caged-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/caged-mcp-server", "--version"
  end
end
